### ISSUE TITLE
Fichiers de logs

### ISSUE THREAD

**Issue by toulet** [tdurieux/server_ftp#8]
Impossible d'executer le serveur chez moi à cause de fichier de log qu'il ne trouve pas.
As-tu ce problème chez toi ?

/usr/lib/jvm/java-1.7.0-openjdk-amd64/jre/bin/java -jar ftp_server.jar

Exception in thread "main" java.lang.RuntimeException: java.io.IOException: Couldn't get lock for file:/home/iwa/git/server_ftp/ftp_server.jar!/lille1/car2014/durieux_toulet/logs/server_ftp.err
    at lille1.car2014.durieux_toulet.logs.LoggerUtilities.<init>(LoggerUtilities.java:57)
    at lille1.car2014.durieux_toulet.logs.LoggerUtilities.getInstance(LoggerUtilities.java:63)
    at lille1.car2014.durieux_toulet.logs.LoggerUtilities.log(LoggerUtilities.java:70)
    at lille1.car2014.durieux_toulet.ftp_server.FTPServerImpl.startServer(FTPServerImpl.java:66)
    at lille1.car2014.durieux_toulet.ftp_server.Main.main(Main.java:25)
Caused by: java.io.IOException: Couldn't get lock for file:/home/iwa/git/server_ftp/ftp_server.jar!/lille1/car2014/durieux_toulet/logs/server_ftp.err
    at java.util.logging.FileHandler.openFiles(FileHandler.java:389)
    at java.util.logging.FileHandler.<init>(FileHandler.java:254)
    at lille1.car2014.durieux_toulet.logs.LoggerUtilities.<init>(LoggerUtilities.java:41)
    ... 4 more

**Comment by tdurieux** [comment]
No ca passe chez moi, je propose de supprimer l'écriture des logs dans les fichiers. Ca règlera pas mal de problème.

**Comment by toulet** [comment]
Bonne idée.

Le 11 février 2014 17:39, Thomas Durieux notifications@github.com a écrit
:

> No ca passe chez moi, je propose de supprimer l'écriture des logs dans les
> fichiers. Ca règlera pas mal de problème.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/tdurieux/server_ftp/issues/8#issuecomment-34772936
> .

## 

_Cyrille Toulet_

**Comment by toulet** [comment]
Tu t'en charges ou je m'en occupe ?

**Comment by toulet** [comment]
Il suffit d'ecrire dirrectement sur stdout plutot que dans un fichier.

**Comment by tdurieux** [comment]
non meme pas besoin il suffit de supprimer tous se qui est relatif au fichier dans le fichier LogUtility.java. Ca s'affichera sur stdout.

Je veux bien le faire si tu vois pas très bien ce que je veux dire

**Comment by toulet** [comment]
Je m'en charge ;-)

**Comment by tdurieux** [comment]
Si tu vois d'autre trucs à changer n'hésite pas. J'ai du faire des trucs un peu tordu pour arriver à un coverage plus ou moins descent.

**Comment by toulet** [comment]
Fait.

**Comment by toulet** [comment]
Je fini de m'occuper des tests unitaires en CLI, puis je relis tout le code.
Je terminerai par tout documenter et ajouter javadoc dans le Makefile.

Le 11 février 2014 17:56, Thomas Durieux notifications@github.com a écrit
:

> Si tu vois d'autre trucs à changer n'hésite pas. J'ai du faire des trucs
> un peu tordu pour arriver à un coverage plus ou moins descent.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/tdurieux/server_ftp/issues/8#issuecomment-34774877
> .

## 

_Cyrille Toulet_
